### ISSUE TITLE
Error: The `add-path` command is deprecated

### ISSUE THREAD

**Issue by EwoutH** [ilammy/setup-nasm#7] opened 2020-11-10 10:35 UTC
Currently `setup-nasm v1.1.0` gives the following error:
> Error: The `add-path` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by ilammy** [comment] 2020-11-10 19:12
I believe this should have been fixed by #6. However, those changes have not been released yet.

@EwoutH, I guess once your other changes are merged, I'll do a release and this warning should go away. This needs to happen soon, before 2020-11-16.

**Comment by ilammy** [comment] 2020-11-13 13:45
Alrighty. `setup-nasm v1.2.0` has been released, that should resolve this warning as it's using updated `@actions/core`. (Well, it does look like that to me.)

@EwoutH could you please confirm the fix?

**Comment by EwoutH** [comment] 2020-11-13 14:22
When explicitly specifying `@v1.2.0` it [works](https://github.com/EwoutH/libavif/runs/1396200405#step:4:1)!

For some reason it isn't defaulting to v1.2.0 yet when just [ilammy/setup-nasm@v1](https://github.com/AOMediaCodec/libavif/pull/410/checks?check_run_id=1396178820#step:4:1) is specified.

**Closed** 2020-11-13 14:24 UTC

**Comment by ilammy** [comment] 2020-11-13 14:41
> For some reason it isn't defaulting to v1.2.0 yet when just ilammy/setup-nasm@v1 is specified.

Sorry, my bad, I forgot to push the updated tag 😂 Now v1 should use the v1.2.0, as intended.
